import Head from 'next/head';
import styles from '@/styles/Home.module.css';
import { motion } from 'framer-motion';

export default function Home() {
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main className={styles.main}>
				<h1 className="text-green-500">Portfolio</h1>
				<motion.div
					initial={{ opacity: 0 }}
					animate={{ opacity: 1 }}
					transition={{ duration: 2 }}>
					<p className="text-green-500">Hello World</p>
				</motion.div>
			</main>
		</>
	);
}
