import Head from 'next/head';
import styles from '@/styles/Home.module.css';
import Toolbar from '@/components/util/toolbar';
import Welcome from '@/components/welcome';
import About from '@/components/about';
import Projects from '@/components/projects';

export default function Home() {
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main className={styles.main}>
				<Toolbar />
				<div className="flex flex-col">
					<section id="home" className="snap-start">
						<Welcome />
					</section>
					<section id="about" className="snap-center">
						<About />
					</section>
					<section id="projects" className="snap-center">
						<Projects />
					</section>
				</div>
			</main>
		</>
	);
}
